# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-d relaxed]
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.1
    hooks:
      - id: gitlab-ci-linter
        name: GitLab CI/CD configuration check
        description: Validates .gitlab-ci.yml file
